	; przypisujemy adresy
	mov	Txt0,ebx
	add	ebx,Txt0_size

	mov	Txt1,ebx
	add	ebx,Txt1_size

	mov	Txt2,ebx
	add	ebx,Txt2_size

	mov	Txt3,ebx
	add	ebx,Txt3_size

	mov	Txt4,ebx
	add	ebx,Txt4_size

	mov	Txt5,ebx
	add	ebx,Txt5_size

	mov	Txt6,ebx
	add	ebx,Txt6_size

	mov	Txt7,ebx
	add	ebx,Txt7_size

	mov	Txt8,ebx
	add	ebx,Txt8_size

	mov	Txt9,ebx
	add	ebx,Txt9_size

	mov	Txt10,ebx
	add	ebx,Txt10_size

	mov	Txt11,ebx
	add	ebx,Txt11_size

	mov	Txt12,ebx
	add	ebx,Txt12_size

	mov	Txt13,ebx
	add	ebx,Txt13_size

	mov	Txt14,ebx
	add	ebx,Txt14_size

	mov	Txt15,ebx
	add	ebx,Txt15_size

	mov	Temp_Seg1,ebx
	add	ebx,Temp_Seg1_size

	mov	Temp_Seg2,ebx
	add	ebx,Temp_Seg2_size

	mov	Temp_Seg3,ebx
	add	ebx,Temp_Seg3_size

	mov	Temp_Seg4,ebx
	add	ebx,Temp_Seg4_size

	mov	Temp_Seg5,ebx
	add	ebx,Temp_Seg5_size

	mov	Temp_Seg6,ebx
	add	ebx,Temp_Seg6_size

	mov	Temp_Seg7,ebx
	add	ebx,Temp_Seg7_size

	mov	Temp_Seg8,ebx
	add	ebx,Temp_Seg8_size

	mov	Temp_Seg9,ebx
	add	ebx,Temp_Seg9_size

	mov	Vhmap,ebx
	add	ebx,Vhmap_size

	mov	envmap,ebx
	add	ebx,envmap_size

	mov	envmap8,ebx
	add	ebx,envmap8_size

	mov	Flare1,ebx
	add	ebx,Flare1_size

	mov	Flare2,ebx
	add	ebx,Flare2_size

	mov	Flare3,ebx
	add	ebx,Flare3_size

	mov	Flare4,ebx
	add	ebx,Flare4_size

	mov	Flare5,ebx
	add	ebx,Flare5_size

	mov	Flare6,ebx
	add	ebx,Flare6_size

	mov	SFlare,ebx
	add	ebx,SFlare_size

	mov	UVBuffer,ebx
	add	ebx,UVBuffer_size

	mov	UVBuffer2,ebx
	add	ebx,UVBuffer2_size

	mov	UVBuffer3,ebx
	add	ebx,UVBuffer3_size

