Txt0	   dd ? 					;
Txt0_size  EQU 256*256*4				; 790528
							;
Txt1	   dd ? 					;
Txt1_size  EQU 256*256*4				; 790528
							;
Txt2	   dd ? 					;
Txt2_size  EQU 256*256*4				; 1052672
							;
Txt3	   dd ? 					;
Txt3_size  EQU 256*256*4				; 1314816 +3145728
							;
Txt4	   dd ? 					;
Txt4_size  EQU 256*256*4				;
							;
Txt5	   dd ? 					;
Txt5_size  EQU 256*256*4				;
							;
Txt6	   dd ? 					;
Txt6_size  EQU 256*256*4				;
							;
Txt7	   dd ? 					;
Txt7_size  EQU 256*256*4				;
							;
Txt8	   dd ? 					;
Txt8_size  EQU 256*256*4				;
							;
Txt9	   dd ? 					;
Txt9_size  EQU 256*256*4				;
							;
Txt10	    dd ?					;
Txt10_size  EQU 256*256*4				;
							;
Txt11	    dd ?					;
Txt11_size  EQU 256*256*4				;
							;
Txt12	    dd ?					;
Txt12_size  EQU 256*256*4				;
							;
Txt13	    dd ?					;
Txt13_size  EQU 256*256*4				;
							;
Txt14	    dd ?					;
Txt14_size  EQU 256*256*4				;
							;
Txt15	    dd ?					;
Txt15_size  EQU 256*256*4*4				  ; 4460544
							;
Temp_Seg1	dd ?					;
Temp_Seg1_size	equ 256*256				 ;
							;
Temp_Seg2	dd ?					;
Temp_Seg2_size	equ 256*256				 ;
							;
Temp_Seg3	dd ?					;
Temp_Seg3_size	equ 256*256				 ;
							;
Temp_Seg4	dd ?					;
Temp_Seg4_size	equ 256*256				 ;
							;
Temp_Seg5	dd ?					;
Temp_Seg5_size	equ 256*256				 ;
							;
Temp_Seg6	dd ?					;
Temp_Seg6_size	equ 256*256				 ;
							;
Temp_Seg7	dd ?					;
Temp_Seg7_size	equ 256*256				 ;
							;
Temp_Seg8	dd ?					;
Temp_Seg8_size	equ 256*256				 ;
							;
Temp_Seg9	dd ?					;
Temp_Seg9_size	equ 256*256				; 5050368
							;
Vhmap	    dd ?					;
Vhmap_size  EQU 256*256 				; 5115904
							;
envmap	     dd ?					;
envmap_size  EQU 256*256*4				;

envmap8       dd ?					 ;
envmap8_size  EQU 256*256				 ;
							;
Flare1	     dd ?					;
Flare1_size  EQU 256*256*4				;
							;
Flare2	     dd ?					;
Flare2_size  EQU 256*256*4				;
							;
Flare3	     dd ?					;
Flare3_size  EQU 256*256*4				;
							;
Flare4	     dd ?					;
Flare4_size  EQU 256*256*4				;
							;
Flare5	     dd ?					;
Flare5_size  EQU 256*256*4				;
							;
Flare6	     dd ?					;
Flare6_size  EQU 256*256*4				; 5574656
							;
SFlare	     dd ?					;
SFlare_size  EQU 64*64*4				;
							;

UVBuffer       dd ?					  ;
UVBuffer_size  EQU 41*26*3*2				    ;

UVBuffer2	dd ?					   ;
UVBuffer2_size	EQU 41*26*3*2				     ;

UVBuffer3	dd ?					   ;
UVBuffer3_size	EQU 41*26*3*2				     ;
